// 15 Real YouTube courses with proper video IDs
export const YOUTUBE_COURSES = [
  {
    id: 'yt-1',
    title: 'Complete React Developer Course 2024',
    description: 'Master React from scratch. Learn hooks, state management, routing, and build real-world projects with modern React patterns.',
    thumbnail: 'https://img.youtube.com/vi/f55qeKGgB_M/maxresdefault.jpg',
    category: 'Web Development',
    level: 'Beginner',
    duration: '12h 30m',
    instructor: 'Traversy Media',
    rating: 4.8,
    students: 128420,
    lessons: [
      { id: 'l1', title: 'Introduction to React', videoUrl: 'https://www.youtube.com/watch?v=f55qeKGgB_M', duration: '45m' },
      { id: 'l2', title: 'React Hooks Deep Dive', videoUrl: 'https://www.youtube.com/watch?v=dpw9EHDh2bM', duration: '1h 20m' },
      { id: 'l3', title: 'State Management with Context', videoUrl: 'https://www.youtube.com/watch?v=35lXWvCuM8o', duration: '55m' },
      { id: 'l4', title: 'React Router v6', videoUrl: 'https://www.youtube.com/watch?v=59IXY5IDrBA', duration: '40m' },
    ]
  },
  {
    id: 'yt-2',
    title: 'Full Stack JavaScript Bootcamp',
    description: 'Complete full stack development with Node.js, Express, MongoDB. Build REST APIs and connect to a React frontend.',
    thumbnail: 'https://img.youtube.com/vi/7CqJlxBYj-M/maxresdefault.jpg',
    category: 'Web Development',
    level: 'Intermediate',
    duration: '15h 45m',
    instructor: 'Academind',
    rating: 4.9,
    students: 203150,
    lessons: [
      { id: 'l1', title: 'Node.js Fundamentals', videoUrl: 'https://www.youtube.com/watch?v=7CqJlxBYj-M', duration: '1h 30m' },
      { id: 'l2', title: 'Building REST APIs', videoUrl: 'https://www.youtube.com/watch?v=0oXYLzuucwE', duration: '2h' },
      { id: 'l3', title: 'MongoDB & Mongoose', videoUrl: 'https://www.youtube.com/watch?v=DZBGEVgL2eE', duration: '1h 15m' },
    ]
  },
  {
    id: 'yt-3',
    title: 'Python for Everybody',
    description: 'Learn Python programming from zero. Variables, data structures, functions, OOP, and build real projects.',
    thumbnail: 'https://img.youtube.com/vi/rfscVS0vtbw/maxresdefault.jpg',
    category: 'Programming',
    level: 'Beginner',
    duration: '10h',
    instructor: 'freeCodeCamp',
    rating: 4.9,
    students: 512000,
    lessons: [
      { id: 'l1', title: 'Python Basics', videoUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw', duration: '2h' },
      { id: 'l2', title: 'Functions & Loops', videoUrl: 'https://www.youtube.com/watch?v=8124kv-632k', duration: '1h 30m' },
      { id: 'l3', title: 'Data Structures', videoUrl: 'https://www.youtube.com/watch?v=W8KRzm-HUcc', duration: '1h 45m' },
      { id: 'l4', title: 'OOP in Python', videoUrl: 'https://www.youtube.com/watch?v=JeznW_7DlB0', duration: '1h 20m' },
    ]
  },
  {
    id: 'yt-4',
    title: 'Machine Learning with Python',
    description: 'Comprehensive ML course covering supervised learning, neural networks, and practical projects with scikit-learn and TensorFlow.',
    thumbnail: 'https://img.youtube.com/vi/GwIo3gDZCVQ/maxresdefault.jpg',
    category: 'AI & ML',
    level: 'Intermediate',
    duration: '20h',
    instructor: 'Sentdex',
    rating: 4.7,
    students: 87340,
    lessons: [
      { id: 'l1', title: 'ML Fundamentals', videoUrl: 'https://www.youtube.com/watch?v=GwIo3gDZCVQ', duration: '1h' },
      { id: 'l2', title: 'scikit-learn Basics', videoUrl: 'https://www.youtube.com/watch?v=0B5eIE_1vpU', duration: '1h 30m' },
      { id: 'l3', title: 'Neural Networks', videoUrl: 'https://www.youtube.com/watch?v=aircAruvnKk', duration: '2h' },
    ]
  },
  {
    id: 'yt-5',
    title: 'CSS Masterclass — Modern Layouts',
    description: 'Master CSS Grid, Flexbox, animations, and modern design techniques. Build beautiful, responsive websites from scratch.',
    thumbnail: 'https://img.youtube.com/vi/1Rs2ND1ryYc/maxresdefault.jpg',
    category: 'Design',
    level: 'Beginner',
    duration: '8h',
    instructor: 'Kevin Powell',
    rating: 4.9,
    students: 164200,
    lessons: [
      { id: 'l1', title: 'CSS Grid Complete Guide', videoUrl: 'https://www.youtube.com/watch?v=EiNiSFIPIQE', duration: '1h' },
      { id: 'l2', title: 'Flexbox Mastery', videoUrl: 'https://www.youtube.com/watch?v=u044iM9xsWU', duration: '45m' },
      { id: 'l3', title: 'CSS Animations', videoUrl: 'https://www.youtube.com/watch?v=1Rs2ND1ryYc', duration: '1h 20m' },
      { id: 'l4', title: 'Responsive Design', videoUrl: 'https://www.youtube.com/watch?v=bn-DQznEZwk', duration: '55m' },
    ]
  },
  {
    id: 'yt-6',
    title: 'TypeScript Full Course',
    description: 'Learn TypeScript from the ground up. Types, interfaces, generics, decorators, and integrating TypeScript with React.',
    thumbnail: 'https://img.youtube.com/vi/gieEQFIfgYc/maxresdefault.jpg',
    category: 'Web Development',
    level: 'Intermediate',
    duration: '9h',
    instructor: 'Fireship',
    rating: 4.8,
    students: 93500,
    lessons: [
      { id: 'l1', title: 'TypeScript Basics', videoUrl: 'https://www.youtube.com/watch?v=gieEQFIfgYc', duration: '30m' },
      { id: 'l2', title: 'Interfaces & Types', videoUrl: 'https://www.youtube.com/watch?v=ahCwqrYpIuM', duration: '45m' },
      { id: 'l3', title: 'Generics', videoUrl: 'https://www.youtube.com/watch?v=nViEqpgwxHE', duration: '40m' },
    ]
  },
  {
    id: 'yt-7',
    title: 'Next.js 14 — App Router Mastery',
    description: 'Build production apps with Next.js 14. Server components, streaming, data fetching, authentication, and deployment.',
    thumbnail: 'https://img.youtube.com/vi/ZVnjOPwW4ZA/maxresdefault.jpg',
    category: 'Web Development',
    level: 'Advanced',
    duration: '14h',
    instructor: 'Theo',
    rating: 4.7,
    students: 45800,
    lessons: [
      { id: 'l1', title: 'Next.js App Router', videoUrl: 'https://www.youtube.com/watch?v=ZVnjOPwW4ZA', duration: '1h 30m' },
      { id: 'l2', title: 'Server Components', videoUrl: 'https://www.youtube.com/watch?v=jmDuM-Cqv2o', duration: '1h' },
      { id: 'l3', title: 'Authentication', videoUrl: 'https://www.youtube.com/watch?v=w2h54xz6Ndw', duration: '1h 20m' },
    ]
  },
  {
    id: 'yt-8',
    title: 'Docker & Kubernetes Fundamentals',
    description: 'Learn containerization and orchestration. Docker containers, Docker Compose, Kubernetes clusters, and CI/CD pipelines.',
    thumbnail: 'https://img.youtube.com/vi/fqMOX6JJhGo/maxresdefault.jpg',
    category: 'DevOps',
    level: 'Intermediate',
    duration: '11h',
    instructor: 'TechWorld with Nana',
    rating: 4.9,
    students: 178900,
    lessons: [
      { id: 'l1', title: 'Docker Fundamentals', videoUrl: 'https://www.youtube.com/watch?v=fqMOX6JJhGo', duration: '2h' },
      { id: 'l2', title: 'Docker Compose', videoUrl: 'https://www.youtube.com/watch?v=DM65_JyGxCo', duration: '1h 30m' },
      { id: 'l3', title: 'Kubernetes Basics', videoUrl: 'https://www.youtube.com/watch?v=s_o8dwzRlu4', duration: '2h 30m' },
    ]
  },
  {
    id: 'yt-9',
    title: 'Data Structures & Algorithms',
    description: 'Master DSA with visual explanations. Arrays, trees, graphs, sorting, searching, and dynamic programming.',
    thumbnail: 'https://img.youtube.com/vi/BBpAmxU_NQo/maxresdefault.jpg',
    category: 'Computer Science',
    level: 'Intermediate',
    duration: '18h',
    instructor: 'Abdul Bari',
    rating: 4.9,
    students: 423000,
    lessons: [
      { id: 'l1', title: 'Big O Notation', videoUrl: 'https://www.youtube.com/watch?v=BBpAmxU_NQo', duration: '1h' },
      { id: 'l2', title: 'Sorting Algorithms', videoUrl: 'https://www.youtube.com/watch?v=g-PGLbMth_g', duration: '45m' },
      { id: 'l3', title: 'Binary Trees', videoUrl: 'https://www.youtube.com/watch?v=oSWTXtMglKE', duration: '1h 30m' },
      { id: 'l4', title: 'Dynamic Programming', videoUrl: 'https://www.youtube.com/watch?v=oBt53YbR9Kk', duration: '2h' },
    ]
  },
  {
    id: 'yt-10',
    title: 'SQL & PostgreSQL Bootcamp',
    description: 'Complete database course covering SQL queries, joins, indexes, stored procedures, and PostgreSQL-specific features.',
    thumbnail: 'https://img.youtube.com/vi/qw--VYLpxG4/maxresdefault.jpg',
    category: 'Database',
    level: 'Beginner',
    duration: '8h',
    instructor: 'Amigoscode',
    rating: 4.8,
    students: 156700,
    lessons: [
      { id: 'l1', title: 'SQL Basics', videoUrl: 'https://www.youtube.com/watch?v=qw--VYLpxG4', duration: '1h' },
      { id: 'l2', title: 'Joins & Relations', videoUrl: 'https://www.youtube.com/watch?v=2HVMiPSuyvA', duration: '1h 15m' },
      { id: 'l3', title: 'PostgreSQL Advanced', videoUrl: 'https://www.youtube.com/watch?v=BHwzDmr6d7s', duration: '1h 30m' },
    ]
  },
  {
    id: 'yt-11',
    title: 'Tailwind CSS Crash Course',
    description: 'Learn Tailwind CSS utility-first framework. Build beautiful UIs fast with responsive design and dark mode.',
    thumbnail: 'https://img.youtube.com/vi/UBOj6rqRUME/maxresdefault.jpg',
    category: 'Design',
    level: 'Beginner',
    duration: '5h',
    instructor: 'Traversy Media',
    rating: 4.7,
    students: 234100,
    lessons: [
      { id: 'l1', title: 'Tailwind Basics', videoUrl: 'https://www.youtube.com/watch?v=UBOj6rqRUME', duration: '1h' },
      { id: 'l2', title: 'Responsive & Dark Mode', videoUrl: 'https://www.youtube.com/watch?v=pfaSUYaSgRo', duration: '45m' },
      { id: 'l3', title: 'Custom Components', videoUrl: 'https://www.youtube.com/watch?v=mr15Xzb1Ook', duration: '1h 20m' },
    ]
  },
  {
    id: 'yt-12',
    title: 'Git & GitHub Complete Guide',
    description: 'Master version control. Git basics, branching, merging, pull requests, GitHub Actions CI/CD, and team workflows.',
    thumbnail: 'https://img.youtube.com/vi/RGOj5yH7evk/maxresdefault.jpg',
    category: 'DevOps',
    level: 'Beginner',
    duration: '6h',
    instructor: 'freeCodeCamp',
    rating: 4.8,
    students: 892000,
    lessons: [
      { id: 'l1', title: 'Git Fundamentals', videoUrl: 'https://www.youtube.com/watch?v=RGOj5yH7evk', duration: '1h' },
      { id: 'l2', title: 'Branching & Merging', videoUrl: 'https://www.youtube.com/watch?v=e2IbNHi4uCI', duration: '45m' },
      { id: 'l3', title: 'GitHub Actions', videoUrl: 'https://www.youtube.com/watch?v=R8_veQiYBjI', duration: '2h' },
    ]
  },
  {
    id: 'yt-13',
    title: 'System Design Interview Prep',
    description: 'Crack system design interviews. Load balancers, caching, databases, microservices, and designing scalable systems.',
    thumbnail: 'https://img.youtube.com/vi/MbjObHmDbZo/maxresdefault.jpg',
    category: 'Computer Science',
    level: 'Advanced',
    duration: '16h',
    instructor: 'ByteByteGo',
    rating: 4.9,
    students: 321000,
    lessons: [
      { id: 'l1', title: 'System Design Basics', videoUrl: 'https://www.youtube.com/watch?v=MbjObHmDbZo', duration: '45m' },
      { id: 'l2', title: 'Scaling & Load Balancing', videoUrl: 'https://www.youtube.com/watch?v=K0Ta65OqQkY', duration: '30m' },
      { id: 'l3', title: 'Database Design', videoUrl: 'https://www.youtube.com/watch?v=W2Z7fbCLSTw', duration: '1h 30m' },
      { id: 'l4', title: 'Microservices', videoUrl: 'https://www.youtube.com/watch?v=j3XufmvEMiM', duration: '1h' },
    ]
  },
  {
    id: 'yt-14',
    title: 'Figma UI/UX Design Masterclass',
    description: 'Design beautiful UIs with Figma. Wireframes, prototypes, design systems, auto-layout, and handoff to developers.',
    thumbnail: 'https://img.youtube.com/vi/FTFaQWZBqQ8/maxresdefault.jpg',
    category: 'Design',
    level: 'Beginner',
    duration: '7h',
    instructor: 'DesignCourse',
    rating: 4.7,
    students: 98400,
    lessons: [
      { id: 'l1', title: 'Figma Basics', videoUrl: 'https://www.youtube.com/watch?v=FTFaQWZBqQ8', duration: '1h' },
      { id: 'l2', title: 'Components & Variants', videoUrl: 'https://www.youtube.com/watch?v=k74IrUNaJVk', duration: '1h 15m' },
      { id: 'l3', title: 'Prototyping', videoUrl: 'https://www.youtube.com/watch?v=lTIeZ2ahEkQ', duration: '1h' },
    ]
  },
  {
    id: 'yt-15',
    title: 'AWS Cloud Practitioner Essentials',
    description: 'Complete AWS fundamentals. EC2, S3, Lambda, RDS, networking, IAM, and cloud architecture best practices.',
    thumbnail: 'https://img.youtube.com/vi/NhDYbskXRgc/maxresdefault.jpg',
    category: 'Cloud',
    level: 'Beginner',
    duration: '13h',
    instructor: 'freeCodeCamp',
    rating: 4.8,
    students: 445000,
    lessons: [
      { id: 'l1', title: 'AWS Fundamentals', videoUrl: 'https://www.youtube.com/watch?v=NhDYbskXRgc', duration: '2h' },
      { id: 'l2', title: 'EC2 & S3', videoUrl: 'https://www.youtube.com/watch?v=Ia-UEYYR44s', duration: '1h 30m' },
      { id: 'l3', title: 'Lambda & Serverless', videoUrl: 'https://www.youtube.com/watch?v=iUIWG0h2D84', duration: '1h' },
      { id: 'l4', title: 'VPC & Networking', videoUrl: 'https://www.youtube.com/watch?v=7XnpdZF_COA', duration: '1h 15m' },
    ]
  },
]

export const CATEGORIES = ['All', 'Web Development', 'Programming', 'AI & ML', 'Design', 'DevOps', 'Database', 'Computer Science', 'Cloud']
export const LEVELS = ['All', 'Beginner', 'Intermediate', 'Advanced']
